### ISSUE TITLE
Question: Is Eclipse plugin required?

### ISSUE THREAD

**Issue by michaldo** [topicusonderwijs/m2e-settings#3]
Let's say I have a plugin which can write something to a file.
I can configure the plugin to write Eclipse .settings files
Then I can tie the plugin with initialization Maven phase.
It looks I can get the same result - common Eclipse settings - simpler than your solution, without Eclipse plugin. Just write few files on initialization phase. 

Am I right or did I missed something?

**Comment by haster** [comment]
Thanks for your interest @michaldo.

That is not quite what this plugin does. This plugin, given a .jar with eclipse settings files, will apply these settings to your eclipse automatically (if your project is correctly configured). 

This means that you can maintain a central eclipse settings jar, deploy that on a respository such as artifactory, and have everyone in your organization automatically pulling and applying those settings.

Also, if you don't make it an eclipse pluin, it won't run (correctly) from eclipse and you'll need to do a command line `mvn` call in order to apply (and update) those settings. Our plugin will automatically run as part of the eclipse (maven-) build.

**Comment by michaldo** [comment]
Thanks for answer, @haster 

I must say I'm not convinced that Eclipse plugin is required. I have to build my own prototype and check myself :)

**Comment by haster** [comment]
Very well. :-)
Good luck and drop us a line if you get it working :+1:

**Comment by michaldo** [comment]
My idea is apply simple `unpack`:

    <build>
    <plugins>
    <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
	<executions>
	  <execution>
	    <?m2e execute ?>
	    <goals>
		<goal>unpack</goal>
	    </goals>
	    <phase>initialize</phase>
	    <configuration>
	        <artifactItems>
		    <artifactItem>
			<groupId>abc</groupId>
			<artifactId>settings-archive</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		    </artifactItem>
	         </artifactItems>
	         <outputDirectory>.settings</outputDirectory>
		  <excludes>META-INF/</excludes>
	      </configuration>
	    </execution>
	</executions>
	</plugin>
	</plugins>
	</build>

Unfortunately, after import project to Eclipse I have to refresh it to make unpacked `settings-archive` active

**Comment by paulvi** [comment]
@michaldo Eclipse has option to automatically refresh:

![image](https://user-images.githubusercontent.com/1614482/33869541-3343e122-df44-11e7-9557-5f1d7ee0d23c.png)

They are just not default.
